# Generated by Django 2.2.12 on 2022-01-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersTable',
            new_name='myTable',
        ),
    ]
