# Generated by Django 2.2.12 on 2022-01-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0002_auto_20220118_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myTable',
            new_name='systemUsers',
        ),
        migrations.RenameField(
            model_name='systemusers',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='systemusers',
            old_name='physical_adress',
            new_name='second_name',
        ),
    ]
