# Generated by Django 2.2.12 on 2022-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0003_auto_20220122_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Balance', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='systemusers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='systemusers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='systemusers',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='systemusers',
            name='username',
        ),
        migrations.AddField(
            model_name='systemusers',
            name='Balance',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
