# Generated by Django 2.2.12 on 2022-01-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0004_auto_20220122_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balances',
            name='Balance',
        ),
    ]
