# Generated by Django 2.2.12 on 2022-01-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0005_remove_balances_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balances',
            name='Balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
