# Generated by Django 4.0 on 2022-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0007_auto_20220122_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='starttrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailadress', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='balances',
            old_name='username',
            new_name='email',
        ),
    ]
