# Generated by Django 2.2.12 on 2022-01-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0008_starttrade_rename_username_balances_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='starttrade',
            new_name='starttrader',
        ),
    ]
