# Generated by Django 2.2.12 on 2022-01-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0009_auto_20220123_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starttrader',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
