# Generated by Django 2.2.12 on 2022-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0010_auto_20220123_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='Balance',
            field=models.CharField(max_length=100),
        ),
    ]
