# Generated by Django 2.2.12 on 2022-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralsystem', '0011_auto_20220123_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='Balance',
            field=models.CharField(max_length=100),
        ),
    ]
