# Generated by Django 4.0 on 2022-01-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTable',
            new_name='traders',
        ),
    ]
