# Generated by Django 2.2.12 on 2022-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Investment',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, default=100.0),
        ),
    ]
