# Generated by Django 2.2.12 on 2022-01-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_traders_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='traders',
            name='Balance',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
