# Generated by Django 2.2.12 on 2022-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220123_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='Balance',
            field=models.FloatField(),
        ),
    ]
