# Generated by Django 2.2.12 on 2022-01-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='Balance',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
