# Generated by Django 2.2.12 on 2022-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220123_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='Balance',
            field=models.CharField(max_length=100),
        ),
    ]
