# Generated by Django 2.2.12 on 2022-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_traders_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='traders',
            name='Balance',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
