# Generated by Django 2.2.12 on 2022-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220122_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentcode', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('paymentemail', models.CharField(max_length=100)),
            ],
        ),
    ]
